In [2]:
import pandas as pd

### Woking with JSON

In [3]:
pd.read_json('train.json')

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [4]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-24,1779580802,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-24,1779580802,0.0383
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-24,1779580802,0.6590
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-24,1779580802,0.8540
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-24,1779580802,3.8400
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-24,1779580802,2.4800
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-24,1779580802,0.1720
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-24,1779580802,0.1970
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-24,1779580802,0.2750
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-05-24,1779580802,0.2750

### Working with SQL

In [6]:
!pip install mysql.connector

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: mysql.connector in c:\users\manna\appdata\roaming\python\python311\site-packages (2.2.9)

In [17]:
pip install --upgrade mysql-connector-python

Defaulting to user installation because normal site-packages is not writeable
Collecting mysql-connector-python
  Obtaining dependency information for mysql-connector-python from https://files.pythonhosted.org/packages/75/68/1f7469669ba1b7d70bec4076766f7672190021090d6eb7e9a0ca6097f501/mysql_connector_python-9.7.0-cp311-cp311-win_amd64.whl.metadata
  Downloading mysql_connector_python-9.7.0-cp311-cp311-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.7.0-cp311-cp311-win_amd64.whl (17.7 MB)
   ---------------------------------------- 0.0/17.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/17.7 MB 1.3 MB/s eta 0:00:14
   - -------------------------------------- 0.6/17.7 MB 8.6 MB/s eta 0:00:02
   ---- ----------------------------------- 1.8/17.7 MB 16.7 MB/s eta 0:00:01
   ------- -------------------------------- 3.4/17.7 MB 21.9 MB/s eta 0:00:01
   -------- ------------------------------- 3.7/17.7 MB 18.1 MB/s eta 0:00:01
   -------- ------------------------------- 3.9/17.7 MB 15.5 MB/s eta 0:00:01
   --------- ------------------------------ 4.1/17.7 MB 13.9 MB/s eta 0:00:01
   --------- ------------------------------ 4.3/17.7 MB 13.7 MB/s eta 0:00:01
   --------- ------------------------------ 4.3/17.7 MB 13.7 MB/s eta 0:00:01
   --------- ------------------------------ 4.3/17.7 MB 13.7 MB/s eta 0:00:01
   --------- ------------------------------ 4.3/17.7 MB 13.7 MB/s eta 0:00:01
   --------- ------------------------------ 4.3/17.7 MB 13.7 MB/s eta 0:00:01
   --------- ------------------------------ 4.4/17.7 MB 7.6 MB/s eta 0:00:02
   ---------- ----------------------------- 4.6/17.7 MB 7.4 MB/s eta 0:00:02
   ---------- ----------------------------- 4.8/17.7 MB 7.2 MB/s eta 0:00:02
   ----------- ---------------------------- 5.1/17.7 MB 7.0 MB/s eta 0:00:02
   ------------ --------------------------- 5.3/17.7 MB 7.0 MB/s eta 0:00:02
   ------------ --------------------------- 5.6/17.7 MB 7.0 MB/s eta 0:00:02
   ------------- -------------------------- 5.9/17.7 MB 7.0 MB/s eta 0:00:02
   -------------- ------------------------- 6.2/17.7 MB 7.0 MB/s eta 0:00:02
   -------------- ------------------------- 6.5/17.7 MB 6.8 MB/s eta 0:00:02
   --------------- ------------------------ 6.9/17.7 MB 7.0 MB/s eta 0:00:02
   ---------------- ----------------------- 7.1/17.7 MB 6.9 MB/s eta 0:00:02
   ---------------- ----------------------- 7.3/17.7 MB 6.8 MB/s eta 0:00:02
   ----------------- ---------------------- 7.5/17.7 MB 6.7 MB/s eta 0:00:02
   ----------------- ---------------------- 7.7/17.7 MB 6.6 MB/s eta 0:00:02
   ------------------ --------------------- 8.0/17.7 MB 6.6 MB/s eta 0:00:02
   ------------------ --------------------- 8.3/17.7 MB 6.5 MB/s eta 0:00:02
   ------------------- -------------------- 8.6/17.7 MB 6.5 MB/s eta 0:00:02
   -------------------- ------------------- 8.9/17.7 MB 6.5 MB/s eta 0:00:02
   -------------------- ------------------- 9.1/17.7 MB 6.5 MB/s eta 0:00:02
   --------------------- ------------------ 9.3/17.7 MB 6.4 MB/s eta 0:00:02
   --------------------- ------------------ 9.5/17.7 MB 6.3 MB/s eta 0:00:02
   ---------------------- ----------------- 9.7/17.7 MB 6.3 MB/s eta 0:00:02
   ---------------------- ----------------- 9.9/17.7 MB 6.2 MB/s eta 0:00:02
   ---------------------- ----------------- 10.1/17.7 MB 6.2 MB/s eta 0:00:02
   ----------------------- ---------------- 10.3/17.7 MB 6.2 MB/s eta 0:00:02
   ----------------------- ---------------- 10.5/17.7 MB 6.1 MB/s eta 0:00:02
   ------------------------ --------------- 10.7/17.7 MB 6.0 MB/s eta 0:00:02
   ------------------------ --------------- 10.9/17.7 MB 5.8 MB/s eta 0:00:02
   ------------------------- -------------- 11.1/17.7 MB 5.7 MB/s eta 0:00:02
   ------------------------- -------------- 11.3/17.7 MB 5.5 MB/s eta 0:00:02
   ------------------------- -------------- 11.4/17.7 MB 5.4 MB/s eta 0:00:02
   -------------------------- ------------- 11.5/17.7 MB 5.3 MB/s eta 0:00:02
   -------------------------- ------------- 11.7/17.7 MB 5.2 MB/s eta 0:00:02
   -------------------------- ------------- 11.9/17.7 MB 5.1 MB/s eta 0:00:02
   --------------------------- ------------ 12.1/17.7 MB 5.1 MB/s eta 0:00:02
   --------------------------- ------------ 12.3/17.7 MB 5.0 MB/s eta 0:00:02
   ---------------------------- ----------- 12.6/17.7 MB 4.8 MB/s eta 0:00:02
   ----------------------------- ---------- 12.9/17.7 MB 4.8 MB/s eta 0:00:02
   ----------------------------- ---------- 13.1/17.7 MB 4.7 MB/s eta 0:00:01
   ------------------------------ --------- 13.4/17.7 MB 4.6 MB/s eta 0:00:01
   ------------------------------ --------- 13.7/17.7 MB 4.5 MB/s eta 0:00:01
   ------------------------------- -------- 13.9/17.7 MB 4.5 MB/s eta 0:00:01
   -------------------------------- ------- 14.2/17.7 MB 4.5 MB/s eta 0:00:01
   -------------------------------- ------- 14.4/17.7 MB 4.5 MB/s eta 0:00:01
   --------------------------------- ------ 14.6/17.7 MB 5.0 MB/s eta 0:00:01
   --------------------------------- ------ 14.8/17.7 MB 5.0 MB/s eta 0:00:01
   --------------------------------- ------ 15.0/17.7 MB 5.0 MB/s eta 0:00:01
   ---------------------------------- ----- 15.2/17.7 MB 5.0 MB/s eta 0:00:01
   ---------------------------------- ----- 15.4/17.7 MB 5.0 MB/s eta 0:00:01
   ----------------------------------- ---- 15.7/17.7 MB 5.0 MB/s eta 0:00:01
   ----------------------------------- ---- 15.9/17.7 MB 5.0 MB/s eta 0:00:01
   ------------------------------------ --- 16.1/17.7 MB 4.9 MB/s eta 0:00:01
   ------------------------------------ --- 16.2/17.7 MB 4.9 MB/s eta 0:00:01
   ------------------------------------- -- 16.4/17.7 MB 4.8 MB/s eta 0:00:01
   ------------------------------------- -- 16.5/17.7 MB 4.7 MB/s eta 0:00:01
   ------------------------------------- -- 16.7/17.7 MB 4.7 MB/s eta 0:00:01
   -------------------------------------- - 16.9/17.7 MB 4.7 MB/s eta 0:00:01
   -------------------------------------- - 17.1/17.7 MB 4.6 MB/s eta 0:00:01
   ---------------------------------------  17.3/17.7 MB 4.6 MB/s eta 0:00:01
   ---------------------------------------  17.6/17.7 MB 4.6 MB/s eta 0:00:01
   ---------------------------------------  17.7/17.7 MB 4.6 MB/s eta 0:00:01
   ---------------------------------------  17.7/17.7 MB 4.6 MB/s eta 0:00:01
   ---------------------------------------  17.7/17.7 MB 4.6 MB/s eta 0:00:01
   ---------------------------------------- 17.7/17.7 MB 4.4 MB/s eta 0:00:00
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.7.0
Note: you may need to restart the kernel to use updated packages.

In [32]:
!pip install pymysql

Defaulting to user installation because normal site-packages is not writeable
Collecting pymysql
  Obtaining dependency information for pymysql from https://files.pythonhosted.org/packages/c4/bd/2534e130295c8cfd4f0a2e31623baab7502278f1e97bcfe61db75656a77f/pymysql-1.2.0-py3-none-any.whl.metadata
  Downloading pymysql-1.2.0-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.2.0-py3-none-any.whl (45 kB)
   ---------------------------------------- 0.0/45.7 kB ? eta -:--:--
   ----------------- ---------------------- 20.5/45.7 kB 682.7 kB/s eta 0:00:01
   ---------------------------------------- 45.7/45.7 kB 771.2 kB/s eta 0:00:00
Installing collected packages: pymysql
Successfully installed pymysql-1.2.0

In [47]:
import pymysql

conn = pymysql.connect(
    host='localhost',
    user='root',
    password='1309',
    database='xyz_company'
)
print("Connected successfully")

Connected successfully

In [48]:
df = pd.read_sql_query("SELECT * FROM emp_info",conn)
df

C:\Users\manna\AppData\Local\Temp\ipykernel_18764\844804919.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql_query("SELECT * FROM emp_info",conn)

   id   name  salary
0   1   adam   25000
1   2    bob   30000
2   3  casey   40000